@startuml 演習３－４
object "車:車" as car{
    
}
object "車:タイヤ" as タイヤ1{
    
}
object "車:タイヤ" as タイヤ2{
    
}
object "車:タイヤ" as タイヤ3{
    
}
object "車:タイヤ" as タイヤ4{
    
}
car--タイヤ1
car--タイヤ2
car--タイヤ3
car--タイヤ4

@enduml